rules_folder: my_rules
run_every:
    seconds: 10
buffer_time:
    seconds: 5
es_host: localhost
es_port: 9200
#es_username: someusername
#es_password: somepassword
writeback_index: elastalert_status
alert_time_limit:
    days: 1